parameters:
  - name: dependencies
    type: object
jobs:
  - job: PostDeployment
    pool:
        name: 'Azure Pipelines'
        vmImage: 'windows-latest'
    dependsOn:
      - "${{ each dependency in parameters.dependencies }}":
         - "${{dependency}}" 
    steps:
      - task: GitHubRelease@1
        displayName: 'GitHub release (create)'
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master') , eq(variables['System.JobAttempt'], '1'), eq(variables['environmentName'], 'prd'))
        inputs:
          gitHubConnection: SkillsFundingAgency
          tagSource: userSpecifiedTag
          tag: '$(Build.BuildNumber)'