{
 "title": "PR CIP - Resac App Service Resource Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Average Response Time (RESAC)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "alias": "{{resourcename}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "$$hashKey": "object:405", "text": "None", "value": "None" },
       { "$$hashKey": "object:406", "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/sites",
      "metricName": "HttpResponseTime",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "s126p01-resac-rg",
      "resourceName": "s126p01-resac-as",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:396", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:397", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:398", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:399", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:400", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:401", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:402", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:403", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:404", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "1e228f79-a66b-4ecb-a695-d5d11808d832"
    },
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "alias": "{{resourcename}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "$$hashKey": "object:428", "text": "None", "value": "None" },
       { "$$hashKey": "object:429", "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/sites",
      "metricName": "HttpResponseTime",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "s126p01-resac-rg",
      "resourceName": "s126p01-resacapi-as",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:419", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:420", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:421", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:422", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:423", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:424", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:425", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:426", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:427", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "1e228f79-a66b-4ecb-a695-d5d11808d832"
    },
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "alias": "{{resourcename}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "$$hashKey": "object:451", "text": "None", "value": "None" },
       { "$$hashKey": "object:452", "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/sites",
      "metricName": "HttpResponseTime",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "s126p01-resac-rg",
      "resourceName": "s126p01-resacintapi-as",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:442", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:443", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:444", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:445", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:446", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:447", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:448", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:449", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:450", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "1e228f79-a66b-4ecb-a695-d5d11808d832"
    }
   ]
  },
  {
   "title": "Storage account Ingress/Egress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "Total",
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "$$hashKey": "object:798", "text": "None", "value": "None" },
       { "$$hashKey": "object:799", "text": "Geo type", "value": "GeoType" },
       { "$$hashKey": "object:800", "text": "API name", "value": "ApiName" },
       { "$$hashKey": "object:801", "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts",
      "metricName": "Ingress",
      "metricNamespace": "Microsoft.Storage/storageAccounts",
      "resourceGroup": "s126p01-resac-rg",
      "resourceName": "s126p01resacstr",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:789", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:790", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:791", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:792", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:793", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:794", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:795", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:796", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:797", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "1e228f79-a66b-4ecb-a695-d5d11808d832"
    },
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "Total",
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "$$hashKey": "object:839", "text": "None", "value": "None" },
       { "$$hashKey": "object:840", "text": "Geo type", "value": "GeoType" },
       { "$$hashKey": "object:841", "text": "API name", "value": "ApiName" },
       { "$$hashKey": "object:842", "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts",
      "metricName": "Egress",
      "metricNamespace": "Microsoft.Storage/storageAccounts",
      "resourceGroup": "s126p01-resac-rg",
      "resourceName": "s126p01resacstr",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:830", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:831", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:832", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:833", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:834", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:835", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:836", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:837", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:838", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "1e228f79-a66b-4ecb-a695-d5d11808d832"
    }
   ]
  },
  {
   "title": "ASP Memory and CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "$$hashKey": "object:657", "text": "None", "value": "None" },
       { "$$hashKey": "object:658", "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/serverFarms",
      "metricName": "CpuPercentage",
      "metricNamespace": "Microsoft.Web/serverFarms",
      "resourceGroup": "s126p01-resac-rg",
      "resourceName": "s126p01-resac-asp",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:648", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:649", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:650", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:651", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:652", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:653", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:654", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:655", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:656", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "1e228f79-a66b-4ecb-a695-d5d11808d832"
    },
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "$$hashKey": "object:668", "text": "None", "value": "None" },
       { "$$hashKey": "object:669", "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/serverFarms",
      "metricName": "MemoryPercentage",
      "metricNamespace": "Microsoft.Web/serverFarms",
      "resourceGroup": "s126p01-resac-rg",
      "resourceName": "s126p01-resac-asp",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:659", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:660", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:661", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:662", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:663", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:664", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:665", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:666", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:667", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "1e228f79-a66b-4ecb-a695-d5d11808d832"
    }
   ]
  },
  {
   "title": "Storage account transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": ""
     },
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "$$hashKey": "object:973", "text": "None", "value": "None" },
       { "$$hashKey": "object:974", "text": "Response type", "value": "ResponseType" },
       { "$$hashKey": "object:975", "text": "Geo type", "value": "GeoType" },
       { "$$hashKey": "object:976", "text": "API name", "value": "ApiName" },
       { "$$hashKey": "object:977", "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts",
      "metricName": "Transactions",
      "metricNamespace": "Microsoft.Storage/storageAccounts",
      "resourceGroup": "s126p01-resac-rg",
      "resourceName": "s126p01resacstr",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:964", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:965", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:966", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:967", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:968", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:969", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:970", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:971", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:972", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "1e228f79-a66b-4ecb-a695-d5d11808d832"
    }
   ]
  }
 ]
}